### ISSUE TITLE
Allow specifying the sizes of nodes

### ISSUE THREAD

**Issue by andriyDev** [paddison/rust-sugiyama#7]
Today, AFAIK the only way to control the distance between nodes is through vertex spacing. This is a fixed amount of spacing between each node. Unfortunately this doesn't allow nodes to account for their size.

For example, I want each node to hold a string which can sometimes be fairly long. This means I either need to allow nodes to overlap which looks really bad, or I need to use a comically large vertex spacing, which makes parts of the graph that are small harder to read. 

Ideally the crate would allow me to give it the size of each node and it would use that to decide where to put the nodes so they don't overlap.

**Comment by dolezvo1** [comment]
I just started looking into this and I think I'm almost done. Surprisingly it seems you only need to add the size to the `Vertex` struct and modify the `execute_phase_3` function a little bit to account for the different sizes. Expect a PR today-ish.

**Comment by dolezvo1** [comment]
This is what I have at the moment. I think I can fix Beth & Summer (i.e. center nodes across ranks), but not sure about Rick not being in between Jerry & Beth.

![sugi](https://github.com/user-attachments/assets/c0a52adf-e7af-4cc1-86fa-3095c3e463ad)

**Comment by dolezvo1** [comment]
I just noticed this paragraph in the readme:

> Finally, the implementation for coordinate assignment follows the algorithm provided by Brandes and Koepf, which can be found in this [paper](https://www.semanticscholar.org/paper/Fast-and-Simple-Horizontal-Coordinate-Assignment-Brandes-K%C3%B6pf/69cb129a8963b21775d6382d15b0b447b01eb1f8).

I'll try to look into that, it sounds like there might be useful information in there.

**Comment by andriyDev** [comment]
> This is what I have at the moment. I think I can fix Beth & Summer (i.e. center nodes across ranks), but not sure about Rick not being in between Jerry & Beth.
> 
> ![sugi](https://private-user-images.githubusercontent.com/171785643/389668097-c0a52adf-e7af-4cc1-86fa-3095c3e463ad.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDY2MzMsIm5iZiI6MTczMjY0NjMzMywicGF0aCI6Ii8xNzE3ODU2NDMvMzg5NjY4MDk3LWMwYTUyYWRmLWU3YWYtNGNjMS04NmZhLTMwOTVjM2U0NjNhZC5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxODM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjcyNTQzMDBjZDc5NGQ5YWJhZDQ3ZTYwZGZlNDdhMGJmYzYwZmExZjBiNTQzZWFkMWJhZmE2OTYyZWMzZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B7c1Egi1jD3T34-9iumWXfeo5lIAShhqw-fhHb50HlQ)

I'm not sure what your settings are like, but this looks to me like we're only pushing nodes left by the vertex spacing, but pushing the next node right by vertex spacing +width. That might be why Jerry is moving only a bit left and Morty isn't moving at all (I would say Morty should be moving a little bit left to make space for Summer so it is more centered).
